### ISSUE TITLE
PES Editing with your tool !

### ISSUE THREAD

**Issue by FirasZinou** [Atvaark/FtexTool#10]
Hi mate i'm from PES editing community and i'm asking you for help about ftex files similair to what you patched in xentax .
"They can also be unpacked by my patched tool.
https://my.mixtape.moe/ntfndx.zip

I won't be releasing the patch because I can't test if it breaks converting other textures and this bug only appears with <1% of all textures I guess."

when convert .ftex to .dds with your tool it comes with black dds so i think your patched tool is the solution for this problem ...

**Comment by Atvaark** [comment]
You could give it a try, but I guess the PES texture format is a different one and there is no guarante that it'll work.
[Debug.zip](https://github.com/Atvaark/FtexTool/files/1308948/Debug.zip)

**Comment by FirasZinou** [comment]
PES FTEX files don't have other ftexs here is an exemple of files : 
[Test.zip](https://github.com/Atvaark/FtexTool/files/1308971/Test.zip)

**Comment by Atvaark** [comment]
Check if this can convert all the PES textures to DDS.
[FtexTool v0.3.3_PES.zip](https://github.com/Atvaark/FtexTool/files/1309079/FtexTool.v0.3.3_PES.zip)

**Comment by FirasZinou** [comment]
yes it converts very well now we need the dds to ftex convert without extra ftexs

**Comment by NaniPesEDIT** [comment]
Atvaark please can you make dds to ftex tool pes editing need you

**Comment by NaniPesEDIT** [comment]
and thanks for ftextool v0.3.3_PES

**Comment by NaniPesEDIT** [comment]
IT IS A IMPORTANT TOOL FOR US
