### ISSUE TITLE
PES 2018 DDS settings are unknown

### ISSUE THREAD

**Issue by Chuny-PES** [Atvaark/FtexTool#13]
Hey!
Thank you for still developing this very useful tool.

I'm still having problems converting a .DDS file with this settings, to FTEX.

![image](https://user-images.githubusercontent.com/33184315/33697543-3de32c62-dae6-11e7-85cb-4ebd2e20decd.png)

In case you're wondering why would I want to use those settings, well the reason if very simple: Because that's how PES 2018 understands Color LUTs. That's how PES 2017 read them too, however PES 2017 still wasn't using .FTEX file format, so we could still use straight .DDS. But now, we have to convert them in order for PES 2018 to pick them up.

I hope you can help me.

If you want to contact me: federico.deblasio@hotmail.com

**Comment by Chuny-PES** [comment]
I tried with these settings as well, but no luck.


![pes lut dds save settings](https://user-images.githubusercontent.com/33184315/33697631-a4570b12-dae6-11e7-864f-5e5bffc94beb.jpg)

**Comment by Atvaark** [comment]
You'll have to figure out the required settings by manually converting one of the games files to DDS. Take the raw data (without headers) of the ftex file and prepend a hand crafted DDS header.
If your DDS viewer can display it propery it's probably the right settings.

**Comment by Chuny-PES** [comment]
No idea how to do anything you just said mate. Sorry! :/

**Comment by Chuny-PES** [comment]
@Atvaark Mate I think you misunderstood me.
There are different type of FTEX files in PES.
Most of them can be converted using your tool (or Tunizizou's tool) with no problem.

The only one that's having problems are the LUT textures. 
I don't know if you know what a LUT is, but it's something like this:

![lut - copia](https://user-images.githubusercontent.com/33184315/33797530-b1519eb4-dce8-11e7-9d82-a121d117b017.png)

Basically this file gives the color information to the game. So if you want to do color-correction, you can do it by simply editing this file in Photoshop and the game will look as you want. Kind of a native Reshade, but much better because it comes FROM the game itself.

This uses a specific settings which is the one I showed you above. However neither your tool nor Tuniziziou is able to conver this particular set of DDS settings back to FTEX. And there's no "unknown" settings here. It's exactly what I've shown above. 8.8.8.8 ABGR 32bpp unsigned, Volume Texture, or 32.32.32f ABGR 128bpp floating point Volume Texture.

I would love you to give us a helping hand here. I can send you both the original FTEX file, the original file converted to DDS , and then the edited file saved as DDS which can't be converted back to FTEX.

**Comment by Atvaark** [comment]
Afaik MGSV used A8R8G8B8 16x16x16 **without MIP maps**. Are you sure you tried every combination?
Also you haven't even written what your issue is besides not knowing which settings to use. Does the tool crash or does the game crash or what?

**Comment by Chuny-PES** [comment]
@Atvaark I don't think you understand what I'm saying here: I DO know what settings to use. I used the settings I showed above for PES 2017. But PES 2017 read DDS files, there was no need to convert to FTEX last year. But this year, with PES 2018 we need to convert to FTEX, so when I save the DDS file with the same settings I used for PES 2017, your tool crashes. The usual Windows 10 message when a program crashes, not much else to report/say.

I don't know why you keep saying I don't know what settings to use, when I've done this a thousand times in the past. It's just that it seems your tool still doesn't support the settings I posted screenshots for above, 3 days ago.

**Comment by Atvaark** [comment]
Have you ever thought about posting **the actual error message** or uploading the crash dump. You do know that I can't really help you if I can't reproduce your issue. This is like googling *computer doesn't work* and expecting to find a solution.

Also you can't be sure a new version of a game is using the same settings as a previous one. It might as well require DX10 DDS files now, but I guess you don't want to do any research/work yourself.

**Comment by Chuny-PES** [comment]
@Atvaark 

![crash](https://user-images.githubusercontent.com/33184315/33811736-65ec5afa-ddf5-11e7-8df1-7f2278159d8d.jpg)

That's all I get when I drag and drop the DDS into your FTEX TOOL V0.4.0, no crash dump I can see. Or tell me where to find it and I will upload it.

Please quit that attitude man, I'm only trying to get help from the developer of this tool, which is a great one. I might be doing something wrong, but I've tried pretty much everything. I've even downloaded Intel's DDS plugin and exported it as a DX10 DDS file. I'm willing to try everything you say, just guide me through it because I'm an editor not a developer.

**Comment by Atvaark** [comment]
Just run the tool in the command line like it's supposed to be run. You can't even specify flags when you drag and drop files on the exe.

Crash dumps are created if you don't cancel that error dialog and should be in *%localappdata%\CrashDumps*.

You'd have to upload the dump or just send me the exception text like above when using your **A8R8G8B8 without mip maps** file.  The files I created and tried didn't cause a single crash.

**Comment by Chuny-PES** [comment]
@Atvaark OK mate. I will do that as soon as I get home from work and then let you know. If it doesn't work, I will upload the CrashDump file.

Thanks a lot.

**Comment by Chuny-PES** [comment]
@Atvaark 
I've been able to convert the DDS now using the command line.
But it generates two files from the "lut.dds" single file.
lut.ftex             -1kb
lut.1.ftexs         -87kb

Can you tell me which one should I use or how to pack it all into a single file like PES uses?.
Only then I will be able to test it ingame and see if it works or it crashes.

Oh may I add that PES original FTEX files are between 8 and 10kb, and when they are converted to DDS, the size is between 16 and 17kb.

**Comment by Atvaark** [comment]
> Can you tell me which one should I use or how to pack it all into a single file like PES uses?.

Read the readme / release notes.

> Oh may I add that PES original FTEX files are between 8 and 10kb,

Original ftexs files are likely zlib compressed. Repacked ones simply aren't. This wasn't an issue in MGSV.
