### ISSUE TITLE
Program closes immediately after opening it.

### ISSUE THREAD

**Issue by NJWarrior12** [Atvaark/FtexTool#14]
As the title states, the program closes immediately after opening it on Windows 10 64bit. Trying to convert multiple .ftex files in a single folder, instead of dragging and dropping each file onto the executable.
Trying to drag and drop multiple files at once crashes the program.
![ftextools](https://user-images.githubusercontent.com/35175364/34642672-e9f082da-f30e-11e7-8c13-6b7ff346b6ac.png)

**Comment by Atvaark** [comment]
You should have read the README.
Multiple files as input isn't even supported. You can either specify a single file or a single folder if you want to unpack all the ftex files inside that folder.
