### ISSUE TITLE
Unknown PixelFormatType 9

### ISSUE THREAD

**Issue by leus** [Atvaark/FtexTool#16]
```
D:\Tools\FtexDdsTools.exe hair_parts_nrm.ftex

Unhandled Exception: System.ArgumentException: Unknown PixelFormatType 9

   at FtexTool.FtexDdsConverter.ConvertToDds(FtexFile file)
   at FtexTool.Program.UnpackFtexFile(String filePath, String outputPath)
   at FtexTool.Program.Main(String[] args)
```
Here's the file. I know you probably won't add support, but I'm leaving this here just in case:
[hair_parts_nrm.zip](https://github.com/Atvaark/FtexTool/files/4566638/hair_parts_nrm.zip)

**Comment by Atvaark** [comment]
Is this from one of the newer soccer games again?

**Comment by leus** [comment]
Yeah, sorry about that. Your tools are used profusely within that community.

**Comment by Atvaark** [comment]
See #15.
I'm not planning on adding support for newer or modified formats or games.
