### ISSUE TITLE
Unicorn Overlord support

### ISSUE THREAD

**Issue by dgyst** [Atvaark/FtexTool#19]
Hi. Please add support for this game if possible. The files come with an extension .ftx but through the hex editor the FTEX header. I attach the files for analysis. https://drive.google.com/file/d/18V9MuObLI3oc4LnVwb1x4bv12k0h2mco/view?usp=sharing

**Comment by Atvaark** [comment]
Doesn't look like a fox engine file format for me. Try asking other modding communities for support.

Anyway this should be enough to split these archives into their components.

```
//------------------------------------------------
//--- 010 Editor v12.0.1 Binary Template
//
//      File: Unicorn Overlord FTX Archive
//   Authors: Atvaark
//   Version: 1
//   Purpose: 
//  Category: Archive
// File Mask: *.ftx
//  ID Bytes: 46 54 45 58
//   History: 
//------------------------------------------------

typedef struct {
  char signature[4]; // FTEX

  short u1; // 320 x count
  short u2; // 8 64 128
  int offset_data;
  int count;
  byte u3[16]; // 0

} Header;

typedef struct {
  char name[32];
  int u1;
  int len;
  int type;
  short u2;
  short u3;
} FileHeader;


typedef struct (int arraySize) {
  byte header[64];
  byte data[arraySize];
} FileData <optimize=false>;

typedef struct {
  char signature[4]; // FEOC
  int u1;
  int u2;
  int u3;
} Footer;

Header header;

FileHeader fileHeaders[header.count];

FSeek(header.offset_data);

local int i;
local int position = FTell(); 
for(i = 0; i < header.count; i++) {
  FileData data(fileHeaders[i].len);
}

Footer footer;

```

I can't give you any info on the pixel format used in these textures.
DXT5 or BC5 appears somewhat right.
![image](https://github.com/Atvaark/FtexTool/assets/5101884/a50c0825-b1ae-4667-86e6-167307603751)

**Comment by dgyst** [comment]
Thank you very much for the help you provided!
