### ISSUE TITLE
OverflowException when converting .DDS to .FTEX

### ISSUE THREAD

**Issue by DiglidiDudeNG** [Atvaark/FtexTool#2]
**File :** nvidia_clp_nmp.dds
**Location :** Metal Gear Solid Ground Zeroes\data_01\Assets\tpp\ui\ModelAsset\sys_logo\Pictures
**How to reproduce :** 
- Create a texture of the same size (2048x1024 in e.g.) in Photoshop using Nvidia's DDS Format converter plugin.
- Convert the DDS file to FTEX by drag&dropping that file on ftextool.exe

**Exact files used :** https://www.mediafire.com/?ba9zu2b19tkpnaf
**Screenshot :** http://prntscr.com/5plp32

That should cover it. Keep in mind that I've been able to do texture modifications on other files without a problem in the past, so this is quite abnormal.

**Comment by DiglidiDudeNG** [comment]
Also if you're curious as to what I'm trying to do: it's for a fake WiiU Trailer I'm making.

**Comment by Atvaark** [comment]
Thanks for your finding. Fox Engine textures use 1-10 mip maps.
You didn't generate any mipmaps in your example dds file.

I'll release a fix for importing mipmapless dds files some time later.
