### ISSUE TITLE
Please tell me how to use it

### ISSUE THREAD

**Issue by programreviewer345** [Atvaark/FtexTool#5]

**Comment by Atvaark** [comment]
Hey, what did you try so far?

**Comment by programreviewer345** [comment]
I was using old version sorry new version works when I drag files onto the exe, but some files don't work with it and make the tool crash.

**Comment by Atvaark** [comment]
The tool should only crash when using it with PS3/360 files or when you are missing some ftexs files.

Run it in a command prompt and check the error message that gets printed. If it mentions any missing .ftexs files then you have to find them in the other game archives and if it doesn't then just post the error message here.

**Comment by Atvaark** [comment]
Any update on this?

**Comment by programreviewer345** [comment]
Yeah it kinda works but when I edit textures they are messed up in
game,using paint.net program
